export default {
  addEmployee: "Add New",
  searchPlaceholder: "Search employees...",
  deleteConfirmation: "Are you sure you want to delete this employee asd?",
  editEmployee: "Edit Employee",
  title: "Employee List",
  paginationNext: "Next",
  employmentDate: "Date of Employment",
  paginationPrevious: "Previous",
  email: "Email",
  dateOfBirth: "Date of Birth",
  updateEmployee: "Update Employee",
  phone: "Phone",
  listView: "List",
  lastName: "Last Name",
  firstName: "First Name",
  tableView: "Table",
  position: "Position",
  department: "Department",
  delete: "Delete",
  edit: "Edit",
  actions: "Actions",
  no: "Cancel",
  yes: "Proceed",
  lastNameRequired: "Last name is required.",
  firstNameRequired: "First name is required.",
  searchPlaceholder: "Search employees...",
  emailRequired: "Email is required.",
  departmentRequired: "Department is required.",
  confirmDelete: "Are you sure?",
  phoneRequired: "Phone number is required.",
  positionRequired: "Position is required.",
  employmentDateRequired: "Employment date is required.",
  confirmSubmit: "Confirm Submission",
  areYouSureSubmit: "Are you sure you want to update this employee?",
  dateOfBirthRequired: "Date of birth is required.",
  employeeAdded: "Added successfully.",
  employeeUpdated: "Updated successfully.",
  deleteDetail: "Selected employee record will be permanently deleted.",
};
