export default {
  addEmployee: "Yeni Ekle",
  deleteConfirmation: "Bu çalışanı silmek istediğinize emin misiniz?",
  searchPlaceholder: "Çalışanları ara...",
  paginationNext: "İleri",
  paginationPrevious: "Geri",
  employmentDate: "İşe Giriş Tarihi",
  editEmployee: "Çalışan Düzenle",
  title: "Çalışan Listesi",
  email: "Email",
  dateOfBirth: "Doğum Tarihi",
  updateEmployee: "Bilgileri Güncelle",
  firstName: "İsim",
  lastName: "Soyad",
  actions: "Aksiyon",
  position: "Pozisyon",
  phone: "Telefon",
  department: "Departman",
  searchPlaceholder: "Çalışanlarda ara..",
  delete: "Sil",
  edit: "Düzenle",
  no: "Hayır",
  yes: "Evet",
  confirmDelete: "Bu çalışanı silmek istediğinizden emin misiniz?",
  firstNameRequired: "İsim gerekli.",
  tableView: "Tablo",
  listView: "Liste",
  lastNameRequired: "Soyad gerekli.",
  departmentRequired: "Departman seçiniz",
  dateOfBirthRequired: "Tarih giriniz.",
  phoneRequired: "Numara gerekli",
  positionRequired: "Posizyon seçiniz",
  employmentDateRequired: "Tarih giriniz.",
  emailRequired: "Email gerekli",
  areYouSureSubmit: "Bilgiler güncellensin mi?",
  confirmSubmit: "Onaylıyor musunuz?",
  employeeUpdated: "Başarılı bir şekilde güncellendi.",
  employeeAdded: "Başarılı bir şekilde eklendi.",
  no: "Hayır",
  yes: "Evet",
};
